[package]
name = "risingwave_connector"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
anyhow = "1"
apache-avro = { git = "https://github.com/risingwavelabs/avro", branch = "waruto/modify-decimal", features = [
    "snappy",
    "zstandard",
    "bzip",
    "xz",
] }
async-trait = "0.1"
aws-config = { workspace = true }
aws-sdk-ec2 = { workspace = true }
aws-sdk-kinesis = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-smithy-http = { workspace = true }
aws-types = { workspace = true }
bincode = "1"
byteorder = "1"
bytes = { version = "1", features = ["serde"] }
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "std",
] }
csv = "1.2"
duration-str = "0.5.0"
enum-as-inner = "0.5"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = { workspace = true }
globset = "0.4.8"
google-cloud-pubsub = "0.14"
hex = "0.4"
http = "0.2"
http-serde = "1.1.0"
hyper = "0.14"
hyper-tls = "0.5"
itertools = "0.10"
maplit = "1.0.2"
moka = { version = "0.10", features = ["future"] }
nexmark = { version = "0.2", features = ["serde"] }
num-traits = "0.2"
parking_lot = "0.12"
prometheus = { version = "0.13", features = ["process"] }
prost = { version = "0.11.0", features = ["no-recursion-limit"] }
prost-reflect = "0.9.2"
protobuf-native = "0.2.1"
pulsar = { version = "4.2", default-features = false, features = [
    "tokio-runtime",
    "telemetry",
    "auth-oauth2",
] }
rdkafka = { workspace = true, features = [
    "cmake-build",
    "ssl",
    "gssapi",
    "zstd",
] }
reqwest = { version = "0.11", features = ["json"] }
risingwave_common = { path = "../common" }
risingwave_pb = { path = "../prost" }
risingwave_rpc_client = { path = "../rpc_client" }
rust_decimal = "1"
serde = { version = "1", features = ["derive", "rc"] }
serde_derive = "1"
serde_json = "1"
serde_with = { version = "2", features = ["json"] }
simd-json = "0.9.1"
tempfile = "3"
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tokio-retry = "0.3"
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["codec", "io"] }
tonic = { version = "0.2", package = "madsim-tonic" }
tracing = "0.1"
url = "2"
urlencoding = "2"
async-nats = "0.29.0"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
criterion = { version = "0.4", features = ["async_tokio", "async"] }
rand = "0.8"
tempfile = "3"

[[bench]]
name = "parser"
harness = false
